DATA_PATH: 'data/complete1129/sample.json'
CLASSES_PATH: 'data/complete1129/classes.json'
DATA_INFO: 'data/complete1129/info.json'
NAME: complete
TIME_ENCODING: external
EPOCHS: 20
TEST_SPLIT: 0.1
BATCH_SIZE: 10
