DATA_PATH: 'data/routines_1029/sample.json'
CLASSES_PATH: 'data/routines_1029/classes.json'
NAME: 
TIME_ENCODING: external
LOSS: MeanLoss
LOSSES_LOG: 
  - MeanLoss
  - ChangedEdgeLoss
  - EdgeTypeLoss
  - MeanLossWhereExists
  - EdgeTypeLossWhereExists
  - SpecificEdgeLoss
EDGES_OF_INTEREST:
EPOCHS: 10
TEST_SPLIT: 0.2
SAMPLE_DATA: True
SAMPLING_RATIO: 1.5