NAME: null
DT: 10
TIME_ENCODING: external
USE_SPECTRAL_LOSS: False
NUM_CHEBYSHEV_POLYS: 2
EDGES_OF_INTEREST: null
EPOCHS: 10
TEST_SPLIT: 0.2
SAMPLE_DATA: True
BATCH_SIZE: 10
ONLY_SEEN_EDGES: False
TREE_FORMULATION: True
IGNORE_CLOSE_EDGES: True
DATA_INFO: null
LEARN_NODES: False
EDGE_IMPORTANCE: True
