DATA_PATH: 'data/routines_1029/sample.json'
CLASSES_PATH: 'data/routines_1029/classes.json'
NAME: 
DT: 10
TIME_ENCODING: external
LOSS: MeanLoss
USE_SPECTRAL_LOSS: True
LOSSES_LOG: 
  - MeanLoss
  - ChangedEdgeWeightedLoss
  - ChangedEdgeLoss
  - EdgeTypeLoss
  - MeanLossWhereExists
  - EdgeTypeLossWhereExists
  - SpecificEdgeLoss
NUM_CHEBYSHEV_POLYS: 2
EDGES_OF_INTEREST:
EPOCHS: 10
TEST_SPLIT: 0.2
SAMPLE_DATA: True
BATCH_SIZE: 10
AVG_SAMPLES_PER_ROUTINE: 10
SEQUENTIAL_PREDICTION: True
