DATA_PATH: 'data/routines_1029/sample.json'
CLASSES_PATH: 'data/routines_1029/classes.json'
NAME: 
TIME_ENCODING: external
LOSS: MeanLoss
LOSSES_LOG: 
  - MeanLoss
  - ChangedEdgeLoss
  - EdgeTypeLoss
  - MeanLossWhereExists
  - EdgeTypeLossWhereExists
EDGES_OF_INTEREST:
EPOCHS: 10
TEST_SPLIT: 0.2
SAMPLE_DATA: True
BATCH_SIZE: 10
AVG_SAMPLES_PER_ROUTINE: 3