NAME: null
DT: 10
TIME_ENCODING: external
EPOCHS: 1
TEST_SPLIT: 0.1
BATCH_SIZE: 5
ONLY_SEEN_EDGES: False
DATA_INFO: null
LEARN_NODES: False
EDGE_IMPORTANCE: predicted
EDGE_DROPOUT_PROB: 0.0
SEARCH_LOOKAHEAD_STEPS: 5
PROACTIVE_LOOKAHEAD_STEPS: 5
ACTION_PROBABILITY_THRESHOLDS: [0.000001,0.0000001]
DETERMINISTIC_INPUT_LOOP: True
DUPLICATION_LOSS_WEIGHT: 0.0
LEARN_CONTEXT: False