NAME: null
DT: 10
TIME_ENCODING: sine_informed
EPOCHS: 2
TEST_SPLIT: 0.1
BATCH_SIZE: 5
ONLY_SEEN_EDGES: False
DATA_INFO: null
LEARN_NODES: False
EDGE_IMPORTANCE: predicted
EDGE_DROPOUT_PROB: 0.15
SEARCH_LOOKAHEAD_STEPS: 5
PROACTIVE_LOOKAHEAD_STEPS: 5
ACTION_PROBABILITY_THRESHOLDS: [0.0,0.0]
DETERMINISTIC_INPUT_LOOP: True
TN_LOSS_WEIGHT: 0.05
LEARN_CONTEXT: False
RUN_BASELINES: True
