NAME: null
DT: 10
TIME_ENCODING: external
LOSS: MeanFilter
USE_SPECTRAL_LOSS: True
LOSSES_LOG: 
  - MeanFilter
  - ChangedEdgeWeightedFilter
  - ChangedEdgeFilter
  - MeanWhereExistsFilter
  - EdgeTypeWhereExistsFilter
  - filters.SpecificEdgeFilter
  - DynamicGraphFilter
NUM_CHEBYSHEV_POLYS: 2
EDGES_OF_INTEREST: null
EPOCHS: 10
TEST_SPLIT: 0.2
SAMPLE_DATA: True
BATCH_SIZE: 10
AVG_SAMPLES_PER_ROUTINE: 10
SEQUENTIAL_PREDICTION: True
ONLY_DYNAMIC_EDGES: False
ALLOW_MULTIPLE_EDGE_TYPES: False
IGNORE_CLOSE_EDGES: True
DATA_INFO: null