NAME: null
DT: 10
TIME_ENCODING: external
EDGES_OF_INTEREST: null
EPOCHS: 2
TEST_SPLIT: 0.2
BATCH_SIZE: 10
ONLY_SEEN_EDGES: False
DATA_INFO: null
LEARN_NODES: False
EDGE_IMPORTANCE: all
EDGE_DROPOUT_PROB: 0.1
