NAME: null
DT: 10
TIME_ENCODING: external
USE_SPECTRAL_LOSS: True
EDGE_LOSS_TRAIN: Mean
EDGE_LOG: 
  - Mean
  - Changed
  - Dynamic
  - Selected
NODE_LOSS_TRAIN: Mean
NODE_LOG: 
  - Mean
NUM_CHEBYSHEV_POLYS: 2
EDGES_OF_INTEREST: null
EPOCHS: 10
TEST_SPLIT: 0.2
SAMPLE_DATA: True
BATCH_SIZE: 10
AVG_SAMPLES_PER_ROUTINE: 10
SEQUENTIAL_PREDICTION: True
ONLY_DYNAMIC_EDGES: False
ALLOW_MULTIPLE_EDGE_TYPES: False
IGNORE_CLOSE_EDGES: True
DATA_INFO: null