DATA_PATH: 'data/routines_1029/sample.json'
CLASSES_PATH: 'data/routines_1029/classes.json'
NAME: 
TIME_ENCODING: external
LOSS: ChangedEdgeLoss
EPOCHS: 5
TEST_SPLIT: 0.1
BATCH_SIZE: 100
AVG_SAMPLES_PER_ROUTINE: 50