DATA_PATH: 'data/routines_1029/sample.json'
CLASSES_PATH: 'data/routines_1029/classes.json'
NAME: SequentialPrediction with SpectralLoss
TIME_ENCODING: external
LOSS: MeanLoss
LOSSES_LOG: 
  - MeanLoss
  - ChangedEdgeLoss
  - EdgeTypeLoss
  - MeanLossWhereExists
EPOCHS: 50
TEST_SPLIT: 0.1
BATCH_SIZE: 100
AVG_SAMPLES_PER_ROUTINE: 50
SEQUENTIAL_PREDICTION: True
USE_SPECTRAL_LOSS: True
