TIME_ENCODING: external
EPOCHS: 10
EDGE_LOSS_TRAIN: Mean
EDGE_LOG: 
  - Mean
  - Changed
  - Dynamic
NODE_LOSS_TRAIN: Mean
NODE_LOG: 
  - Mean
TEST_SPLIT: 0.1
BATCH_SIZE: 10
SEQUENTIAL_PREDICTION: True
USE_SPECTRAL_LOSS: False
ALLOW_MULTIPLE_EDGE_TYPES: False
