TIME_ENCODING: external
LOSS: MeanFilter
LOSSES_LOG: 
  - MeanFilter
  - ChangedEdgeFilter
  - MeanWhereExistsFilter
  - DynamicGraphFilter
EPOCHS: 100
TEST_SPLIT: 0.1
BATCH_SIZE: 10
SEQUENTIAL_PREDICTION: True
USE_SPECTRAL_LOSS: False
ALLOW_MULTIPLE_EDGE_TYPES: False
